### ISSUE TITLE
pygimli.frameworks.harmfit does not work with numpy integers for nc

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#143]
Attempting to use an numpy-derived integer throws an argument error in harmfit.

e.g. Testing different values of nc

Works;
```
for nc in range(1,10):
    print(nc)
    x = np.asarray(pygimli.frameworks.harmfit(xx,tt, nc = nc, resample = np.linspace(0,71,72),robust = robust)[0])
    y = np.asarray(pygimli.frameworks.harmfit(yy,tt, nc = nc, resample = np.linspace(0,71,72),robust = robust)[0])
    z = np.asarray(pygimli.frameworks.harmfit(zz,tt, nc = nc, resample = np.linspace(0,71,72),robust = robust)[0])
    fig, ax = plt.plot(xx,yy, 'bx-',x,y,'r-')
````
Does not work:
```
for nc in np.arange(1,10):
    print(nc)
    x = np.asarray(pygimli.frameworks.harmfit(xx,tt, nc = nc, resample = np.linspace(0,71,72),robust = robust)[0])
    y = np.asarray(pygimli.frameworks.harmfit(yy,tt, nc = nc, resample = np.linspace(0,71,72),robust = robust)[0])
    z = np.asarray(pygimli.frameworks.harmfit(zz,tt, nc = nc, resample = np.linspace(0,71,72),robust = robust)[0])
    fig, ax = plt.plot(xx,yy, 'bx-',x,y,'r-')
Traceback (most recent call last):

  File "<ipython-input-204-57f54da4c1e6>", line 1, in <module>
    np.asarray(pygimli.frameworks.harmfit(xx,tt, nc = nc, resample = np.linspace(0,71,72),robust = robust)[0])

  File "G:\BERT\pygimli\frameworks\harmfit.py", line 131, in harmfit
    fop = pg.HarmonicModelling(nc, xToFit, verbose)

ArgumentError: Python argument types in
    HarmonicModelling.__init__(HarmonicModelling, numpy.int32, numpy.ndarray, bool)
did not match C++ signature:
    __init__(_object*, unsigned long long nh, GIMLI::Vector<double> tvec)
    __init__(_object*, unsigned long long nh, GIMLI::Vector<double> tvec, bool verbose=False)
```

**Comment by carsten-forty2** [comment]
We had no automatic type conversion from numpy scalars to the pygimli core. 

I added them just now (34041b03241f51d6ee16af144c70acb2e5596dce). 

They will be available on the next binary update.

Thanks a lot for reporting.
Carsten
