### ISSUE TITLE
Pygimli import

### ISSUE THREAD

**Issue by AleVin11** [gimli-org/gimli#273]
### Problem description

I can't import Pygimli, it appears an import error.

### Your environment

**Operating system**: Linux Centos 7, server
**Python version**: 3.8
**pyGIMLi version**: pygimli-1.1.1-np118py38hf484d3e_0.tar.bz2
**Way of installation**: conda install etc. etc.

### Steps to reproduce
```python
import pygimli as pg
...
```
### Actual behavior
```Python
>>> import pygimli
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pygimli/__init__.py", line 8, in <module>
    from .core.decorators import (renamed, singleton)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pygimli/core/__init__.py", line 20, in <module>
    from ._pygimli_ import *
SystemError: initialization of _pygimli_ raised unreported exception
>>> 
```

What is the problem?

Thanks

**Comment by carsten-forty2** [comment]
sorry I can't reproduce this problem. I tried:

```
conda create -n pg -c gimli -c conda-forge pygimli=1.1.0
conda activate pg-1.1.1-py38
python -c 'import pygimli as pg; pg.version()'
17/12/20 - 18:00:58 - pyGIMLi - INFO - Version (cached): 1.1.0+0.g47c8d810 (with local changes) core:libgimli-v1.1.0
```

and 

```
conda create -n pg-1.1.1-py38 -c gimli -c conda-forge pygimli=1.1.1 python=3.8
conda activate pg-1.1.1-py38
python -c 'import pygimli as pg; pg.version()'
17/12/20 - 18:05:35 - pyGIMLi - INFO - Version (cached): 1.1.1+0.gf487e7cd (with local changes) core:libgimli-v1.1.1
```

Do you have some PATH or PYTHONPATH settings in your environment showing to different old installations?

**Comment by AleVin11** [comment]
Thank you for your answer.
The problem is that i can't use the command conda create as you used because the server cannot connect outside. So i'm using the base environment. 
I added the PATH to Python3.8.

**Comment by halbmy** [comment]
You mean the server does not have internet? How could you install anything by conda? Downloading the wheels from the anaconda server?

What do you mean you *added the PATH to Python 3.8*? Are you using a built-in Anaconda distribution or a Miniconda? Maybe there is a conflict between the native Python and conda Python.

**Comment by AleVin11** [comment]
Yes, the server that i am using  can't connect outside the network.

Sorry for my inaccuracy but I added the PATH to Python3.8 inside Anaconda.
To start python I digit python3.8 after activating the base environment, at this stage when I import pygimli the error appears

**Comment by halbmy** [comment]
Still the question has not been answered how you installed pyGIMLi and what exactly you downloaded (or copied). We have not generated wheels since we switched to v1.1, and none for Python 3.8 at all (but we should at least provide it for major versions). If you installed pg using conda on another computer and copied the lib/site-package folder, the dynamic libraries are missing.

**Comment by halbmy** [comment]
Ah sorry, I just saw that you obviously downloaded the conda package from https://anaconda.org/gimli/pygimli/files?version=1.1.1 and installed it locally. I never did that and have no idea how conda cares for the dependencies like numpy, boost etc. (do you have to download and install them all by hand?) Make sure you have all dependencies:
        - Python 3.8
        - numpy 1.18
        - matplotlib
        - openblas
        - scipy
        - pytest
        - gxx_{{ target_platform }}
        - suitesparse
        - {{ pin_compatible('py-boost',min_pin='x.x', max_pin='x.x') }}
        - pyvista

**Comment by halbmy** [comment]
Closing due to inactivity.
