### ISSUE TITLE
pygimli installation issue

### ISSUE THREAD

**Issue by Changwan-planet** [gimli-org/gimli#485]
### Problem description

I just tried to install pygimli by using the commands below.

```conda create -n pg -c conda-forge pygimli```

Also

```conda create -n pg -c gimli -c conda-forge pygimli=1.3.1``` 

,and
```conda install -c gimli pygimli```

But, I got this error report below when I used the commands above.
How to deal with this issue?

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 132, in conda_http_errors
        yield
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 101, in repodata
        response.raise_for_status()
      File "/home/changwan/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/gimli/linux-64/current_repodata.json
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/changwan/.local/lib/python3.8/site-packages/requests/models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
        return _default_decoder.decode(s)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
        obj, end = self.raw_decode(s)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 132, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 175, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 280, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 447, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 1060, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 124, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/home/changwan/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
        yield fs.pop().result()
      File "/home/changwan/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 444, in result
        return self.__get_result()
      File "/home/changwan/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
        raise self._exception
      File "/home/changwan/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 113, in <lambda>
        subdir_query = lambda url: tuple(
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 129, in query
        self.load()
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 215, in load
        _internal_state = self._load()
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 323, in _load
        raw_repodata_str = self._repo.repodata(mod_etag_headers)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 101, in repodata
        response.raise_for_status()
      File "/home/changwan/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 179, in conda_http_errors
        raise RepodataIsEmpty(
      File "/home/changwan/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 461, in __init__
        body = response.json()
      File "/home/changwan/.local/lib/python3.8/site-packages/requests/models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /home/changwan/anaconda3/bin/conda create -n pg -c gimli -c conda-forge pygimli`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/changwan/anaconda3/bin/conda
CONDA_MKL_INTERFACE_LAYER_BACKUP=
             CONDA_PREFIX=/home/changwan/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/changwan/anaconda3/bin/python
               CONDA_ROOT=/home/changwan/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/changwan/anaconda3/bin:/home/changwan/anaconda3/condabin:/home/c
                          hangwan/micmac/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/
                          sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/changwan/anaconda3
            shell level : 1
       user config file : /home/changwan/.condarc
 populated config files : /home/changwan/.condarc
          conda version : 23.1.0
    conda-build version : 3.20.5
         python version : 3.8.12.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /home/changwan/anaconda3  (writable)
      conda av data dir : /home/changwan/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/gimli/linux-64
                          https://conda.anaconda.org/gimli/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/changwan/anaconda3/pkgs
                          /home/changwan/.conda/pkgs
       envs directories : /home/changwan/anaconda3/envs
                          /home/changwan/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.8.12 Linux/5.15.0-56-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```

Please help me out...
I met the obstacle in the first step of the pyGIMLI.

Thank you very much,
Changwan

**Comment by halbmy** [comment]
Which of the three calls did produce the above error?

The first one cannot work, as the gimli channel is missing. The third can produce conflicts with the existing env. So we prefer the second (and say this on the website).

**Comment by halbmy** [comment]
To me, it looks like something is wrong with your anaconda installation or with internet connection (e.g. proxy servers to be provided in `.condarc` file). If you can exclude the latter, maybe try again with a fresh installation of miniconda.

**Comment by Changwan-planet** [comment]
Ok! That error came out from my personal laptop computer that cannot handle the second command line. 
The second line is working in the computer in my lab. Thank you so much!

I got this output.
```
>>> print(pg.__version__)
1.3.1
```
