### ISSUE TITLE
How to plot result of the issue #336 

### ISSUE THREAD

**Issue by ishuihan** [gimli-org/gimli#498]
### Problem description

Hello, I have studied the issue #336  carefully, giving me a lot of inspiration, thank you. I have a question about how to plot the result of the inversion. I use the code pg.show(mesh,invmodel), but it doesn't work.

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**: e.g. Windows, Linux or Mac?
**Python version**: e.g. 3.8, 3.9, etc.?
**pyGIMLi version**: Output of `print(pygimli.__version__)`
**Way of installation**: e.g. Conda package, manual compilation from source, etc.

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg
import pygimli.physics.ert as ert
import pygimli.meshtools as mt

data = ert.load("gallery.dat")
mesh = mt.createParaMesh(data, verbose=True)
pg.show(mesh)

fop = ert.ERTModelling()
fop.setData(data)
fop.setMesh(mesh)

inv=pg.Inversion(fop=fop, verbose=True)
inv.setRegularization(10) 

invmodel = inv.run(data['rhoa'], data['err'], startModel=100)

pg.show(mesh, invmodel)
...
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
27/02/23 - 22:53:14 - pyGIMLi - ERROR - None._drawField(D:\program\anaconda3\envs\pg\lib\site-packages\pygimli\viewer\showmesh.py:385)
Data size invalid
Data:  596 3.8045368270518405 150.81885003322046 False
Mesh:  Mesh: Nodes: 451 Cells: 795 Boundaries: 1245
local variable 'gci' referenced before assignment
Traceback (most recent call last):
  File "D:\program\anaconda3\envs\pg\lib\site-packages\pygimli\viewer\showmesh.py", line 413, in showMesh
    gci, validData = _drawField(ax, mesh, data, kwargs)
  File "D:\program\anaconda3\envs\pg\lib\site-packages\pygimli\viewer\showmesh.py", line 392, in _drawField
    return gci, validData
UnboundLocalError: local variable 'gci' referenced before assignment
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by ishuihan** [comment]
It worked. thank you very much. ERTManager is convenient，however, the reason why I use pg.Inversion is to introduce external forward operators, like 6_Inversion_with_any_forward_operator.ipynb in transform2021. But in the example, it is one-dimensional. If the forward operator is two-dimensional, is it OK? @carsten-forty2

**Comment by ishuihan** [comment]
In the above example, fop=ert. ERTModelling() is the built-in two-dimensional forward operator of pygimli. If I use the external two-dimensional forward operator, is it feasible? @carsten-forty2

**Comment by ishuihan** [comment]
Thank you, I will try. To simplify the operation, in the first step, I will replace the pure two-dimensional forward operator with the quasi two-dimensional forward operator (constructed based on the one-dimensional forward operator). Thank you again.
