### ISSUE TITLE
Geostatistical constraints in 3D magnetics

### ISSUE THREAD

**Issue by Socigogo** [gimli-org/gimli#534]
### Problem description

The geostatistical constraints in 3D magnetics inversion don't seem to work.

### Your environment

Operating system: Windows
Python version: 3.8
pyGIMLi version: dev version
Way of installation: Anaconda

### Steps to reproduce

my code:

```python
import numpy as np
import pygimli as pg
from pygimli.viewer import pv
from pygimli.physics.gravimetry import MagneticsModelling

dx = 50
x = np.arange(0., 2001, dx)
y = np.arange(0., 2001, dx)
z = np.arange(0., 1001, dx)
grid = pg.createGrid(x, y, z)
print(grid)

v = np.zeros((len(z)-1, len(y)-1, len(x)-1))

v[6:12, 16:24, 16:24] = 0.4

grid["k/SI"] = v.ravel()


pl, _ = pg.show(grid, style="wireframe", hold=True)
pv.drawMesh(pl, grid, label="k/SI", style="surface", cMap="Spectral_r",
            filter={"threshold": dict(value=0.05, scalars="k/SI")})
pl.camera_position = "yz"
pl.camera.roll = 90
pl.camera.azimuth = 180 - 15
pl.camera.elevation = 10
pl.camera.zoom(1.2)
_ = pl.show()


F, I, D = 49883.7e-9, 47, -4.6
H = F * np.cos(np.deg2rad(I))
X = H * np.cos(np.deg2rad(D))
Y = H * np.sin(np.deg2rad(D))
Z = F * np.sin(np.deg2rad(I))
igrf = [D, I, H, X, Y, Z, F]

py, px = np.meshgrid(x, y)
px = px.ravel()
py = py.ravel()
points = np.column_stack((px, py, -np.ones_like(px)*10))

print(points)
# The forward operator
cmp = ["TFA"]  # ["Bx", "By", "Bz"]
fop = MagneticsModelling(grid, points, cmp, igrf)
model = pg.Vector(grid.cellCount(), 1.0)
data = fop.response(grid["k/SI"])

err = 0.01
noise_level = 1e-9
data += np.random.randn(len(data)) * noise_level

# depth weighting
bz = np.array([b.center().z() for b in grid.boundaries() if not b.outside()])
z0 = 25
wz = 10 / (bz+z0)**1.5

inv = pg.Inversion(fop=fop, verbose=True)  # , debug=True)
inv.setRegularization(limits=[0, 0.5],  correlationLengths=[100, 100, 100], dip=30)  # to limit values
inv.setConstraintWeights(wz)

invmodel = inv.run(data, absoluteError=noise_level, lam=10000, startModel=1e-3, verbose=True)
grid["inv"] = invmodel

pl, _ = pg.show(grid, label="k/SI", style="wireframe", hold=True,
                filter={"threshold": dict(value=0.025, scalars="k/SI")})
pv.drawMesh(pl, grid, label="inv", style="surface", cMap="Spectral_r",
            filter={"threshold": dict(value=0.02, scalars="inv")})
pv.drawMesh(pl, grid, label="inv", style="surface", cMap="Spectral_r",
            filter={"slice": dict(normal=[-1, 0, 0], origin=[500, 600, 250])})
pl.camera_position = "yz"
pl.camera.roll = 90
pl.camera.azimuth = 180 - 15
pl.camera.elevation = 10
pl.camera.zoom(1.2)
_ = pl.show()

### Expected behavior

I want to constrain the 3D magnetic inversion results using the geostatistical constraints.

### Actual behavior

The inversion result is the same as when it was not used.

**Comment by halbmy** [comment]
Which pgcore version are you using? The current version 1.4 is only available for Python 3.9 on Windows. Please check by
```
import pygimli as pg
print(pg.Report())
```

Apart from this, I can confirm that unlike the 2D gravity example (I will make an example from the issue) geostatistical regularization is not used and will fix this.

**Comment by halbmy** [comment]
Thanks! So it is Python 3.9 and pgcore 1.4, but there seems to be a problem with the version in the the conda package for Windows that we need to correct.

The magnetics forward operator could indeed not be used with geostatistical constraints as it was not derived from the `MeshModelling` operator. I changed this (69762122) and now it works.

However, such a big model would require a huge amount of memory as a full eigenvalue decomposition is done. Unless we use another algorithm that uses only a subset, it will not be feasible.

**Comment by Socigogo** [comment]
I got this error after changing the function MagneticsModelling.

C:\Users\86155\anaconda3\envs\pg\lib\site-packages\pygimli\math\matrix.py:457: RuntimeWarning: invalid value encountered in sqrt
  self._mul = np.sqrt(1./self.ew)
Traceback (most recent call last):
  File "D:\python project\Pygimli1.4.0\3Dmagnetics2.py", line 66, in <module>
    invmodel = inv.run(data, absoluteError=noise_level, lam=10000, startModel=1e-3, verbose=True)
  File "C:\Users\86155\anaconda3\envs\pg\lib\site-packages\pygimli\frameworks\inversion.py", line 646, in run
    self.inv.start()
RuntimeError: ./core/src/inversion.cpp:115		double GIMLI::RInversion::getPhiM(const Vec&) const  getPhiM == nan

**Comment by halbmy** [comment]
Looks like an eigenvalue is zero. With the model above? Can't check it now. I had a memory error on my Windows laptop but I will try again on a  bigger Linux machine. Unless we switch to truncated eigenvalue decomposition it will not be feasible for 3D problems.

Can you reproduce the error on a smaller grid?

**Comment by Socigogo** [comment]
Is this grid okay？

dx = 50
x = np.arange(0., 1001, dx)
y = np.arange(0., 1001, dx)
z = np.arange(0., 501, dx)
grid = pg.createGrid(x, y, z)
print(grid)

v = np.zeros((len(z)-1, len(y)-1, len(x)-1))

v[4:7, 8:12, 8:12] = 0.4

I got the same error.

**Comment by halbmy** [comment]
I made a few corrections (3241c8a) to the geostatistic constraints matrix so that only non-negligible (>1e-6) eigenvalues and eigenvectors are stored. This reduces memory consumption and avoids problems with zero or negative (due to numerical inaccuracies) eigenvalues causing your problem. Please check it out with the dev branch.

**Comment by Socigogo** [comment]
Sorry, it's still the same error after the change.

**Comment by halbmy** [comment]
Probably it takes the constraint matrix from the cache. Can you change the mesh size slightly?

**Comment by Socigogo** [comment]
It's useful, my code works now.
But the inversion results are much worse than when geostatistical constraints were not used. That's why?
In addition, I would like to learn more about the principles of geostatistical operators, are there any recommended papers?

**Comment by halbmy** [comment]
Probably you have to play with the parameters, like increasing or decreasing the regularization strength, or the correlation lengths etc. About the principles you can learn from the paper of Jordi et al. (2018) and references therein, and of course from the tutorials

https://www.pygimli.org/_tutorials_auto/3_inversion/plot_5_Regularization.html and

https://www.pygimli.org/_tutorials_auto/3_inversion/plot_6-geostatConstraints.html

Jordi, C., Doetsch, J., Günther, T., Schmelzbach, C. & Robertsson, J.O.A. (2018): Geostatistical regularisation operators for geophysical inverse problems on irregular meshes. Geophysical Journal International 213, 1374-1386, doi:10.1093/gji/ggy055
