### ISSUE TITLE
Provide support for newer compilers via CastXML

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#6]
GCCXML is not supporting newer compiler versions and is replaced by CastXML (https://github.com/CastXML/CastXML). If py++ is ready to work with CastXML (https://github.com/gccxml/pygccxml/issues/19), we should think about switching.

**Comment by carsten-forty2** [comment]
As I can see for now, py++ needs a small tweak to forward the caster=castXML argument to pyplusplus .. but we find a way once pyplusplus works smooth with castXML gccxml-like output.  (gccxml/pygccxml#19)

**Comment by carsten-forty2** [comment]
add support for castxml via cmake setting -DCASTER=castxml default is -DCaster=gccxml. 
castxml is superbuild via cmake .. Not yet fully functional due to pending problem (https://github.com/gccxml/pygccxml/issues/19)

**Comment by florian-wagner** [comment]
:+1:

**Comment by carsten-forty2** [comment]
pygimli can now be build with castxml and gcc|clang

but:

tutorials/inversion/plot-1-polyfit.py brings strange results with castxml 

and still works fine with gccxml.

I will dive into it, but we need some more unittests and or snippets that fail now with castxml

**Comment by florian-wagner** [comment]
I have tried to compile with:

```
CC=clang CXX=clang++ cmake -DCASTER='castxml' -DPYVERSION=3.4.3 ../trunk
```

CMake output looks fine:

```
-- **********************************************************************
-- ************************* Dependencies found *************************
-- **********************************************************************
-- Triangle_LIBRARIES: /home/fwagner/src/gimli/thirdParty/dist-Clang-3.6.1-64/lib/libtriangle.a
-- UMFPACK_LIBRARIES: /lib64/libumfpack.so;/lib64/libcolamd.so;/lib64/libamd.so;/lib64/libsuitesparseconfig.so
-- CHOLMOD_LIBRARIES: /lib64/libcholmod.so;/lib64/libcamd.so;/lib64/libamd.so;/lib64/libcolamd.so;/lib64/libccolamd.so;/lib64/libsuitesparseconfig.so;/lib64/liblapack.so;/lib64/libblas.so;/lib64/libblas.so;/usr/lib/gcc/x86_64-unknown-linux-gnu/4.7.4/libgfortran.so;rt
-- PYTHON_EXECUTABLE: /usr/bin/python
-- PYTHON_LIBRARY: /lib64/libpython3.4m.so
-- Boost_PYTHON_LIBRARIES: /usr/lib64/libboost_python.so
-- GCCXML_EXECUTABLE: 
-- CASTXML_EXECUTABLE: /home/fwagner/src/gimli/thirdParty/dist-Clang-3.6.1-64/bin/castxml
-- XML Caster: /home/fwagner/src/gimli/thirdParty/dist-Clang-3.6.1-64/bin/castxml
-- PYGCCXML: /home/fwagner/src/gimli/thirdParty/dist-Clang-3.6.1-64
-- PYPLUSPLUS: /home/fwagner/src/gimli/thirdParty/dist-Clang-3.6.1-64
-- PY_NUMPY: /usr/lib/python3.4/site-packages/numpy/
-- **********************************************************************
```

Yet pygimli fails with:

```
[100%] Built target gimli
Python version: 3.4
Python lib: /usr/lib/python3.4
['/home/fwagner/src/gimli/trunk/python', '/home/fwagner/.local/lib/python3.4/site-packages/rcs_latexdiff-1.0-py3.4.egg', '/home/fwagner/src/gimli/build/python', '/home/fwagner/Skripte/Python', '/home/fwagner/local/python', '/usr/lib/python34.zip', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-linux', '/usr/lib/python3.4/lib-dynload', '/home/fwagner/.local/lib/python3.4/site-packages', '/usr/lib/python3.4/site-packages', '/usr/lib/python3.4/site-packages/gtk-2.0', '../../../pygccxml', '../../../pyplusplus']
Install SRC:   /home/fwagner/src/gimli/trunk/python/generate_pygimli_code.py
Execute from:  /home/fwagner/src/gimli/build/python
caster_path=/home/fwagner/src/gimli/thirdParty/dist-Clang-3.6.1-64/bin/castxml
working_directory=../src
include_paths=['/usr/include', '/home/fwagner/src/gimli/trunk/src']
define_symbols=['PYGIMLI_GCCXML', 'HAVE_BOOST_THREAD_HPP']
indexing_suite_version=2
Traceback (most recent call last):
  File "/home/fwagner/src/gimli/trunk/python/generate_pygimli_code.py", line 523, in <module>
    generate(defined_symbols, options.extraIncludes)
  File "/home/fwagner/src/gimli/trunk/python/generate_pygimli_code.py", line 246, in generate
    caster=caster
TypeError: __init__() got an unexpected keyword argument 'caster'
```

:birthday: :gift:

**Comment by carsten-forty2** [comment]
I think you need to update pygccxml and pyplusplus.

try:

make rebuild_thirdparty



Quoting Florian Wagner <notifications@github.com>:

**Comment by florian-wagner** [comment]
Ah, I did that, but I had a system-wide pygccxml version lying around... Compiles now. Is there a minimal version of pygccxml that is needed? Than we can incorporate something like:

``` python
pygccxml_minversion = "vX.X"
if caster="castxml" and pygccxml.__version__ < pygccxml_minversion:
    raise Error("pygccxml is too old for castxml, please try 'make rebuild_thirdparty'")
```

Looks like pygimli compiles a bit faster now, is that right?
