### ISSUE TITLE
Pygimli Windows 7 Installation

### ISSUE THREAD

**Issue by Mark-Dunscomb** [gimli-org/gimli#70]
Hi
I've tried to install pygimli several ways and have hit dead ends on all accounts.  Sooo, help would be greatly appreciated. Here's what I've done and the results:

Installed msys2 and followed the installation http://www.pygimli.org/installation.html via curl.
Results in the following error

```$ curl -Ls install.pygimli.org | bash
 ------------------------------------------------------------
|                                                            |
| Geophysical Inversion and Modeling Library (www.gimli.org) |
|                                                            |
 ------------------------------------------------------------
==========================================
Determining system ... Msys WIN64 system found
PYTHON FOUND: 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] 3
VERSION: 3.6
warning: diffutils-3.5-1 is up to date -- skipping
warning: patch-2.7.5-1 is up to date -- skipping
 there is nothing to do
backup /c/Anaconda3/include/pyconfig.h to /c/Anaconda3/include/pyconfig.h.backup
patch hypot gcc bug at line: 241
Difference is:
241,242c241
< //#define hypot _hypot
< #include <cmath>
---
> #define hypot _hypot
------------------------------------------
Installing at /home/mdunscomb/gimli
Build for Python=3
Parallelize with j=2
Update only 0
Branch:
CLEAN build: 0
==========================================
Installing system prerequisites for win64
------------------------------------------
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-binutils-2.28-2

Total Download Size:   12.88 MiB
Total Installed Size:  95.58 MiB
Net Upgrade Size:       0.12 MiB

:: Proceed with installation? [Y/n] echo "#########################
==========================================
Installing gimli for win64
------------------------------------------
~/gimli ~
~/gimli/gimli ~/gimli ~
Already up-to-date.
~/gimli ~
rm: cannot remove 'build/CMakeFiles': Device or resource busy
CLEAN,
~/gimli/build ~/gimli
-- The C compiler identification is GNU 7.1.0
-- The CXX compiler identification is GNU 7.1.0
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target is 64 bits
-- ThirdParty set to: C:/msys64/home/mdunscomb/gimli/gimli/../thirdParty/
-- External set to: C:/msys64/home/mdunscomb/gimli/thirdParty/dist-GNU-7.1.0-64
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found PythonInterp: C:/Anaconda3/python.exe (found version "3.6.1")
-- Checking for package 'TRIANGLE'
-- External dir: C:/msys64/home/mdunscomb/gimli/thirdParty/dist-GNU-7.1.0-64
-- Triangle_INCLUDE_DIR = Triangle_INCLUDE_DIR-NOTFOUND
-- Triangle_LIBRARIES = Triangle_LIBRARIES-NOTFOUND
-- Triangle could not be found. (missing:  Triangle_LIBRARIES Triangle_INCLUDE_DIR)
-- Triangle is local True
-- Found Wget: C:/msys64/usr/bin/wget.exe
-- Found Subversion: C:/msys64/usr/bin/svn.exe (found version "1.9.5")
-- Found Git: C:/msys64/usr/bin/git.exe (found version "2.13.0")
CMake Error at C:/msys64/mingw64/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Hg (missing: HG_EXECUTABLE)
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  C:/msys64/mingw64/share/cmake-3.8/Modules/FindHg.cmake:94 (find_package_handle_standard_args)
  cmake/GIMLImacros.cmake:152 (find_package)
  cmake/GIMLImacros.cmake:193 (findBuildTools)
  cmake/GIMLImacros.cmake:169 (find_or_build_package_check)
  CMakeLists.txt:226 (find_or_build_package)


-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/mdunscomb/gimli/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
~/gimli
~

============================================================================
------------------------  TEST pyGIMLi installation ------------------------
No module named 'pygimli.core._pygimli_'
Traceback (most recent call last):
  File "C:\msys64\home\mdunscomb\gimli\gimli\python\pygimli\core\__init__.py", line 33, in <module>
    from . _pygimli_ import *
ModuleNotFoundError: No module named 'pygimli.core._pygimli_'
ERROR: cannot import the library '_pygimli_'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\msys64\home\mdunscomb\gimli\gimli\python\pygimli\__init__.py", line 18, in <module>
    from . import core
  File "C:\msys64\home\mdunscomb\gimli\gimli\python\pygimli\core\__init__.py", line 43, in <module>
    _pygimli_.load = None
AttributeError: 'NoneType' object has no attribute 'load'
--- ------------------------------------------------------------------------

========================================================================
Set the following setting to use pygimli, either locally
per session or permanently in your /home/mdunscomb/.bashrc
------------------------------------------------------------------------

export PYTHONPATH=/home/mdunscomb/gimli/gimli/python
export PATH=/home/mdunscomb/gimli/gimli/python/apps:$PATH

------------------------------------------------------------------------
```

I added to the path as requested and received the same error so I attempted to install pygimli manually and received this error.

```
$ pacman -S mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-fortran
warning: mingw-w64-x86_64-cmake-3.8.2-2 is up to date -- reinstalling
warning: mingw-w64-x86_64-gcc-7.1.0-2 is up to date -- reinstalling
warning: mingw-w64-x86_64-gcc-fortran-7.1.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (3) mingw-w64-x86_64-cmake-3.8.2-2  mingw-w64-x86_64-gcc-7.1.0-2  mingw-w64-x86_64-gcc-fortran-7.1.0-2

Total Installed Size:  169.10 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] Y
(3/3) checking keys in keyring                                         [#######################################] 100%
(3/3) checking package integrity                                       [#######################################] 100%
(3/3) loading package files                                            [#######################################] 100%
(3/3) checking for file conflicts                                      [#######################################] 100%
(3/3) checking available disk space                                    [#######################################] 100%
:: Processing package changes...
(1/3) reinstalling mingw-w64-x86_64-cmake                              [#######################################] 100%
(2/3) reinstalling mingw-w64-x86_64-gcc                                [#######################################] 100%
(3/3) reinstalling mingw-w64-x86_64-gcc-fortran                        [#######################################] 100%

mdunscomb@00-1510-003 MINGW64 ~
$ pacman -S mingw-w64-x86_64-openblas mingw-w64-x86_64-doxygen
warning: mingw-w64-x86_64-openblas-0.2.17-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-doxygen-1.8.13-4 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (2) mingw-w64-x86_64-doxygen-1.8.13-4  mingw-w64-x86_64-openblas-0.2.17-1

Total Installed Size:  103.94 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] Y
(2/2) checking keys in keyring                                         [#######################################] 100%
(2/2) checking package integrity                                       [#######################################] 100%
(2/2) loading package files                                            [#######################################] 100%
(2/2) checking for file conflicts                                      [#######################################] 100%
(2/2) checking available disk space                                    [#######################################] 100%
:: Processing package changes...
(1/2) reinstalling mingw-w64-x86_64-openblas                           [#######################################] 100%
(2/2) reinstalling mingw-w64-x86_64-doxygen                            [#######################################] 100%

mdunscomb@00-1510-003 MINGW64 ~
$ pacman -S mingw-w64-x86_64-llvm mingw-w64-x86_64-clang
warning: mingw-w64-x86_64-llvm-4.0.0-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-clang-4.0.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (2) mingw-w64-x86_64-clang-4.0.0-1  mingw-w64-x86_64-llvm-4.0.0-1

Total Installed Size:  377.87 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] Y
(2/2) checking keys in keyring                                         [#######################################] 100%
(2/2) checking package integrity                                       [#######################################] 100%
(2/2) loading package files                                            [#######################################] 100%
(2/2) checking for file conflicts                                      [#######################################] 100%
(2/2) checking available disk space                                    [#######################################] 100%
:: Processing package changes...
(1/2) reinstalling mingw-w64-x86_64-llvm                               [#######################################] 100%
(2/2) reinstalling mingw-w64-x86_64-clang                              [#######################################] 100%

mdunscomb@00-1510-003 MINGW64 ~
$ cmake ../trunk -G 'MSYS Makefiles' -DBLAS_LIBRARIES=/mingw64/lib/libopenblas.a
CMake Error: The source directory "C:/msys64/home/trunk" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```
Ok, not installing properly.  Attempted via conda.

```
(C:\Anaconda3) C:\Users\mdunscomb>conda install pygimli
Fetching package metadata ...............

PackageNotFoundError: Package missing in current win-64 channels:
  - pygimli

Close matches found; did you mean one of these?

    pygimli: pugixml
```

No joy.  Any help you can provide would be appreciated.  Thanks

**Comment by carsten-forty2** [comment]
1. attempt:

cmake complains about missing mercurial binary. 'Could NOT find Hg (missing: HG_EXECUTABLE)'


Either you install hg(mercurial)  in your mingw environment using pacman or you wait until I checked why the toolchain does not install them as needed.


2. attempt:

cmake ../trunk -G 'MSYS Makefiles' -DBLAS_LIBRARIES=/mingw64/lib/libopenblas.a

CMake Error: The source directory "C:/msys64/home/trunk" does not exist.


You apparently called cmake from the wrong directory. ../trunk should point to the source repository. (we should clarify this in the installation howto.)


3. attempt:

Unfortunately there is not yet a conda package for windows .. we work on this.


In addition:


It seems mingw recently bumped gcc-7 which we does not tried yet .. I will check this in the next days.


Seems you (or the curl script) wants to build pygimli against anaconda-python for windows .. we did not tried this before and its unknown to be working. However, the curl script should work with a current winpython installation.


(note to myself) We should put a direct download link for windows binary on the webpage in the next days.


Thanks for reporting

**Comment by halbmy** [comment]
There has not been any activity in this Issue. At least we know the curl script is running on some Windows systems with gcc 7.1 (Carsten fixed some stuff in the toolchain), so the reason might be due to firewall or proxy problems. Therefore we should close the issue. In case of enduring problems just open a new one.
