### ISSUE TITLE
Cannot import name 'RVector3' form 'pygimli.core.core

### ISSUE THREAD

**Issue by schaatz** [gimli-org/gimli#721]
### Problem description

When I import pygimli, it showed "cannot import name 'RVector3' form 'pygimli.core.core'".

### Your environment

**Operating system**: Linux 
**Python version**: 3.11.9
**pyGIMLi version**: 1.5.1
**Way of installation**:Conda package

### Steps to reproduce

When I try to run a Python file, I encounter this error, "cannot import name 'RVector3' form 'pygimli.core.core'", but on my Windows system with the same Python and PyGIMLi versions, it doesn't throw an error.

### Expected behavior

No wrong information

### Actual behavior

```
cannot import name 'RVector3' form 'pygimli.core.core'
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by siarw** [comment]
I am having the same problem, but my output has earlier errors. I appreciate any help.

OS: macOS 14.5 (23F79)
Python: 3.11.9
PyGIMLi: pygimli-1.5.1
Installed using: conda

Here's the output.

```
/Users/pedro/miniconda3/envs/pg/bin/python /Users/pedro/Documents/Geophysics/tutorial1.py
dlopen(/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pgcore/_pygimli_.so, 0x0002): Library not loaded: @rpath/libcholmod.3.dylib
  Referenced from: <D05C48BA-33ED-3C63-8331-F97D57235C73> /Users/pedro/miniconda3/envs/pg/lib/libgimli.dylib
  Reason: tried: '/Users/pedro/miniconda3/envs/pg/lib/libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/lib/../lib64/libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pgcore/../../../libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pgcore/../../../../lib64/libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pgcore/../../../libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pgcore/../../../../lib64/libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/bin/../lib/libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/bin/../lib/libcholmod.3.dylib' (no such file)
Traceback (most recent call last):
  File "/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pygimli/core/core.py", line 11, in <module>
    from . import _pygimli_  # if it works: as pgcore, replace all _pygimli_
    ^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name '_pygimli_' from partially initialized module 'pygimli.core' (most likely due to a circular import) (/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pygimli/core/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pgcore/__init__.py", line 20, in <module>
    from ._pygimli_ import *
ImportError: dlopen(/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pgcore/_pygimli_.so, 0x0002): Library not loaded: @rpath/libcholmod.3.dylib
  Referenced from: <D05C48BA-33ED-3C63-8331-F97D57235C73> /Users/pedro/miniconda3/envs/pg/lib/libgimli.dylib
  Reason: tried: '/Users/pedro/miniconda3/envs/pg/lib/libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/lib/../lib64/libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pgcore/../../../libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pgcore/../../../../lib64/libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pgcore/../../../libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pgcore/../../../../lib64/libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/bin/../lib/libcholmod.3.dylib' (no such file), '/Users/pedro/miniconda3/envs/pg/bin/../lib/libcholmod.3.dylib' (no such file)
ERROR: cannot import the library '_pygimli_'.
Traceback (most recent call last):
  File "/Users/pedro/Documents/Geophysics/tutorial1.py", line 1, in <module>
    import pygimli as pg
  File "/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pygimli/__init__.py", line 8, in <module>
    from .core.decorators import (renamed, singleton, moduleProperty,
  File "/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pygimli/core/__init__.py", line 14, in <module>
    from .base import (isInt, isScalar, isIterable, isArray, isPos, isR3Array,
  File "/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pygimli/core/base.py", line 7, in <module>
    from .core import (RVector3, R3Vector, RMatrix)
ImportError: cannot import name 'RVector3' from 'pygimli.core.core' (/Users/pedro/miniconda3/envs/pg/lib/python3.11/site-packages/pygimli/core/core.py)
```

**Comment by ruboerner** [comment]
I encountered a similar problem after installing pygimli-1.5.1 in a fresh environment on a Mac. To solve the problem I had to provide symbolic links in the `lib` folder of the environment.

More precisely: 

Go to the folder where the libraries are:
```sh
cd /Users/xxx/miniconda3/envs/pg/lib
```

Create the following symbolic links
```sh
ln -s libcholmod.5.dylib libcholmod.3.dylib
ln -s libumfpack.6.dylib libumfpack.5.dylib
```

Hope this helps!

Cheers,
Ralph

**Comment by halbmy** [comment]
Obviously we have to change or conda recipies to make sure the runtime versions match the build versions.

**Comment by halbmy** [comment]
We should also avoid the strange error message about `RVector3` and provide an error message that links users back to the installation problems.

**Comment by siarw** [comment]
> I encountered a similar problem after installing pygimli-1.5.1 in a fresh environment on a Mac. To solve the problem I had to provide symbolic links in the `lib` folder of the environment.
> 
> More precisely:
> 
> Go to the folder where the libraries are:
> 
> ```shell
> cd /Users/xxx/miniconda3/envs/pg/lib
> ```
> 
> Create the following symbolic links
> 
> ```shell
> ln -s libcholmod.5.dylib libcholmod.3.dylib
> ln -s libumfpack.6.dylib libumfpack.5.dylib
> ```
> 
> Hope this helps!
> 
> Cheers, Ralph

This solved it. Many thanks, Ralph @ruboerner !

**Comment by halbmy** [comment]
Linkage might not be the solution as shown by #721.

Can you try explicitly specifying suitesparse versions? 
UMFPACK 5 is probably related to suitesparse 6, so maybe adding `suitesparse=6` to the install command?

**Comment by dtiger10** [comment]
> > I encountered a similar problem after installing pygimli-1.5.1 in a fresh environment on a Mac. To solve the problem I had to provide symbolic links in the `lib` folder of the environment.
> > More precisely:
> > Go to the folder where the libraries are:
> > ```shell
> > cd /Users/xxx/miniconda3/envs/pg/lib
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Create the following symbolic links
> > ```shell
> > ln -s libcholmod.5.dylib libcholmod.3.dylib
> > ln -s libumfpack.6.dylib libumfpack.5.dylib
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this helps!
> > Cheers, Ralph
> 
> This solved it. Many thanks, Ralph @ruboerner !

Hello @siarw,

I am running into the exact issue. However I simply implemented the directions above AND my installation still outputs the error that you displayed. Did you do anything beyond initiating those two lines of code in the ./pg/lib/ directory?

Any insight would be appreciative...

Best,
Del

**Comment by florian-wagner** [comment]
For the Mac users (@ruboerner, @siarw, @dtiger10), please see my recommendations here: https://github.com/gimli-org/gimli/issues/730#issuecomment-2830047941

**Comment by krauthex** [comment]
I ran into the same issue today, with pygimli-1.5.4. I tried the same softlink workaround as suggested by @ruboerner, which initially solved the problem. However, I was then running into errors, when using the ERT inversion:
```
fop: <pygimli.physics.ert.ertModelling.ERTModelling object at 0x7fc9c6a67920>
Data transformation: Logarithmic LU transform, lower bound 0.0, upper bound 0.0
Model transformation (cumulative):
        0 Logarithmic LU transform, lower bound 0.0, upper bound 0.0
        1 Logarithmic LU transform, lower bound 0.0, upper bound 0.0
min/max (data): 202/4942
min/max (error): 5%/5.08%
min/max (start model): 30/2000
--------------------------------------------------------------------------------
use model trans from RegionManager
Calculating response for model: min = 30 max = 2000
Allocating memory for primary potential...... 0.0367833
No primary potential for secondary field calculation with topography.
Creating P2-Primmesh:           Nodes: 19431    Cells: 9484     Boundaries: 14457
ModellingBase::setMesh() copying new mesh ... Found topography for surface=1054.24 : 1054.26
Found datafile: 93 electrodes
Found: 93 node-electrodes
rMin = 0.573229, rMax = 271.701
NGauLeg + NGauLag for inverse Fouriertransformation: 16 + 4
Found non-Neumann domain
0.0612011 s
FOP updating mesh dependencies ... 3.75e-06 s
malloc(): invalid size (unsorted)
Aborted (core dumped)
```

So I downgraded to pygimli-1.5.3, which also downgrades `suitesparse`:
```
────────────────────────────────────────────────────────────────────
 Downgrade:
────────────────────────────────────────────────────────────────────
- pygimli        1.5.4  py_0              gimli           Cached
+ pygimli        1.5.3  py_0              gimli            385kB
- suitesparse   7.10.1  ha0f6916_7100102  conda-forge     Cached
+ suitesparse   5.10.1  h5a4f163_3        conda-forge        1MB
```

and with suitesparse-5.10.1 I got the correct libraries that `pygimli` was missing before, eg `libcholmod.so.3` and `libumfpack.so.5` (I recreated my venv to be sure that the libraries are installed and no hacky symlinks remain.)

Now everything works for me. :-) 

For reference, I am running on an Ubuntu 20.06.6.

**Comment by halbmy** [comment]
Thanks for reporting. However, downgrading pyGIMLi should not be the solution. Can you tell us your OS and how you installed pyGIMLi (conda or pip)?

**Comment by krauthex** [comment]
> Thanks for reporting. However, downgrading pyGIMLi should not be the solution. Can you tell us your OS and how you installed pyGIMLi (conda or pip)?

I agree that downgrading should not be the solution, unfortunately I needed a working setup fast (and the code in question was running before already on pygimli-1.5.3, so at least for the moment things are alright. :-) 

OS is Ubuntu 20.04.6, installation method was via `miniforge3` and `mamba` in a virtual environment. The venv was set up with the following conda/mamba venv yaml:
```yaml
name: timelapse
channels:
  - gimli
  - conda-forge
dependencies:
  - python >=3.11,<3.12.0a0 
  - pygimli=1.5.3
  - numpy
  - pandas
  - matplotlib
  - pip
```

Before, of course, `pygimli` was not pinned on 1.5.3 but left free, which would install the version 1.5.4.

**Comment by krauthex** [comment]
> > Thanks for reporting. However, downgrading pyGIMLi should not be the solution. Can you tell us your OS and how you installed pyGIMLi (conda or pip)?
> 
> I agree that downgrading should not be the solution, unfortunately I needed a working setup fast (and the code in question was running before already on pygimli-1.5.3, so at least for the moment things are alright. :-)
> 
> OS is Ubuntu 20.04.6, installation method was via `miniforge3` and `mamba` in a virtual environment. The venv was set up with the following conda/mamba venv yaml:
> 
> name: timelapse
> channels:
>   - gimli
>   - conda-forge
> dependencies:
>   - python >=3.11,<3.12.0a0 
>   - pygimli=1.5.3
>   - numpy
>   - pandas
>   - matplotlib
>   - pip
> 
> Before, of course, `pygimli` was not pinned on 1.5.3 but left free, which would install the version 1.5.4.

To add to this, if I use pygimli-1.5.4, the error I get upon running a script is:
```console
libcholmod.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/perm/operserv/fkrautgasser/miniforge3/envs/test/lib/python3.11/site-packages/pygimli/core/core.py", line 15, in <module>
    from .libs import _pygimli_ as pgcore
ModuleNotFoundError: No module named 'pygimli.core.libs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/perm/operserv/fkrautgasser/miniforge3/envs/test/lib/python3.11/site-packages/pgcore/__init__.py", line 20, in <module>
    from ._pygimli_ import *
ImportError: libcholmod.so.3: cannot open shared object file: No such file or directory
ERROR: cannot import the library '_pygimli_'.
Traceback (most recent call last):
  File "/perm/operserv/fkrautgasser/geo/timelapse-test/Timelapse_COBS.py", line 10, in <module>
    import pygimli as pg
  File "/perm/operserv/fkrautgasser/miniforge3/envs/test/lib/python3.11/site-packages/pygimli/__init__.py", line 8, in <module>
    from .core.decorators import (renamed, singleton, moduleProperty,
  File "/perm/operserv/fkrautgasser/miniforge3/envs/test/lib/python3.11/site-packages/pygimli/core/__init__.py", line 13, in <module>
    from .base import (isInt, isScalar, isIterable, isArray, isPos, isR3Array,
  File "/perm/operserv/fkrautgasser/miniforge3/envs/test/lib/python3.11/site-packages/pygimli/core/base.py", line 7, in <module>
    from .core import (RVector3, R3Vector, RMatrix)
ImportError: cannot import name 'RVector3' from 'pygimli.core.core' (/perm/operserv/fkrautgasser/miniforge3/envs/test/lib/python3.11/site-packages/pygimli/core/core.py)
```

**Comment by halbmy** [comment]
Please try adding
```
  - suitesparse=5
```
to your dependencies in the yml file and try again.

**Comment by krauthex** [comment]
> Please try adding
> 
> ```
>   - suitesparse=5
> ```
> 
> to your dependencies in the yml file and try again.

Hi, sorry for the late reply! Pinning `suitesparse=5` appears to fix the issues, even on `pygimli-1.5.4`. :-)

**Comment by halbmy** [comment]
Great! I leave the issue open as a reminder to update the environment.yml file.
