### ISSUE TITLE
make: *** [pygimli] Error 2

### ISSUE THREAD

**Issue by suhle** [gimli-org/gimli#8]
I'm trying to compile gimli/pygimli on Linux Mint 17 (Kernel Linux 3.13.0-24). I followed the steps as described (i.e. cmake ../trunk/, followed by make gimli and pygimli). Building gimli works without any issues, but when trying to build pygimli I get the following output:

``` bash
[100%] Built target gimli
Scanning dependencies of target pggen
('Python version:', '2.7')
('Python lib:', '/usr/lib/python2.7')
['/home/seb/src/gimli/trunk/python', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '../../../pygccxml', '../../../pyplusplus']
('Install SRC:  ', '/home/seb/src/gimli/trunk/python/generate_pygimli_code.py')
('Execute from: ', '/home/seb/src/gimli/build/python')
gccxml_path=/home/seb/src/gimli/thirdParty/dist-GNU-4.8.2-64/bin/gccxml
working_directory=../src
include_paths=['/usr/include', '/home/seb/src/gimli/trunk/src']
define_symbols=['PYGIMLI_GCCXML', 'HAVE_BOOST_THREAD_HPP']
indexing_suite_version=2
<logging.Logger object at 0x2b76279017d0>
DEBUG Reading project files: file by file
INFO Creating xml file "_pygimli_.cache" from source file "/home/seb/src/gimli/trunk/python/pygimli.h" ... 
INFO gccxml cmd: /home/seb/src/gimli/thirdParty/dist-GNU-4.8.2-64/bin/gccxml  -I"../src" -I"/usr/include" -I"/home/seb/src/gimli/trunk/src"  -D"PYGIMLI_GCCXML" -D"HAVE_BOOST_THREAD_HPP"  "/home/seb/src/gimli/trunk/python/pygimli.h" -fxml="_pygimli_.cache"
INFO Parsing xml file "_pygimli_.cache" ... 
DEBUG Reading xml file: [_pygimli_.cache]
DEBUG File has not been found in cache, parsing...
INFO GCCXML version - 0.9
/usr/lib/pymodules/python2.7/pygccxml/parser/scanner.py:337: UserWarning: unable to find out array size from expression ""
  warnings.warn( msg )
ERROR error occured, while parsing element with name "FundamentalType" and attrs "['attributes', 'align', 'size', 'id', 'name']".
Error: pygccxml error: unable to find fundamental type with name 'atomic_int_type'..
Traceback (most recent call last):
  File "/home/seb/src/gimli/trunk/python/generate_pygimli_code.py", line 476, in <module>
    generate(defined_symbols, options.extraIncludes)
  File "/home/seb/src/gimli/trunk/python/generate_pygimli_code.py", line 226, in generate
    indexing_suite_version=2
  File "/usr/lib/python2.7/dist-packages/pyplusplus/module_builder/builder.py", line 92, in __init__
    , indexing_suite_version)
  File "/usr/lib/python2.7/dist-packages/pyplusplus/module_builder/builder.py", line 146, in __parse_declarations
    decls = reader.read_files( files, compilation_mode )
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/project_reader.py", line 225, in read_files
    return self.__parse_file_by_file(files)
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/project_reader.py", line 264, in __parse_file_by_file
    decls = reader.read_xml_file( prj_file.cached_source_file )
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/source_reader.py", line 245, in read_xml_file
    declarations, files = self.__parse_gccxml_created_file( ffname )
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/source_reader.py", line 294, in __parse_gccxml_created_file
    scanner_.read()
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/etree_scanner.py", line 41, in read
    self.startElement( elem.tag, elem.attrib )
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/scanner.py", line 199, in startElement
    obj = self.__readers[name]( attrs )
  File "/usr/lib/pymodules/python2.7/pygccxml/parser/scanner.py", line 361, in __read_fundamental_type
    % attrs.get( XML_AN_NAME, '' ) )
RuntimeError: pygccxml error: unable to find fundamental type with name 'atomic_int_type'.
make[3]: *** [pggen] Error 1
make[2]: *** [python/CMakeFiles/pggen.dir/all] Error 2
make[1]: *** [CMakeFiles/pygimli.dir/rule] Error 2
make: *** [pygimli] Error 2
```
I'd be very grateful for any help with that!

**Comment by carsten-forty2** [comment]
Please ensure using the current pygccxml version.

Your output indicates an older pygccxml and maybe an older gccxml

INFO Creating xml ...
INFO gccxml cmd: ..
INFO Parsing xml file "_pygimli_.cache" ... 
DEBUG Reading xml file: [_pygimli_.cache]
DEBUG File has not been found in cache, parsing...
INFO GCCXML version - 0.9

The current pygccxml shows the cmd line and version only with DEBUG flags like:

INFO Creating xml .
DEBUG gccxml cmd: .
INFO Parsing xml file "_pygimli_.cache" ... 
DEBUG Reading xml file: [_pygimli_.cache]
DEBUG File has not been found in cache, parsing...
DEBUG GCCXML version - 0.9 ( 1.135 )

It may sufficient to delete the thirdParty dist and build paths .. but to be sure perform a clean rebuild.

I will think about a mechanism to force thirdParty updates.

**Comment by florian-wagner** [comment]
``` python
 import pygccxml; print pygccxml.__path__
['usr/lib/pymodules/python2.7/pygccxml']
```
It seems like a system-wide pygccxml version was used, which caused the problem. We should:
- use the thirdparty pygccxml even if pygccxml is already installed
- probably not list pygccxml as an optional dependency here http://www.pygimli.org/INSTALL.html

Thanks for reporting, Seb!

**Comment by carsten-forty2** [comment]
- Removed some default path hints in cmake find [gccxml/pygccxml] stuff  and added NO_DEFAULT_PATH option. 
- added more verbose cmake output which dependency was found

**Comment by florian-wagner** [comment]
- Restructured installation instructions

**Comment by suhle** [comment]
Thanks for your help! After removing system-wide installed pygccxml and gccxml everything worked without flaws!
